background            #1c2024
foreground            #e0e2e8
selection_foreground  #d5e4f6
cursor                #9acbfa
url_color             #d2bfe7
selection_background  #3a4857
selection_foreground  #d5e4f6
cursor_text_color     #003352

active_tab_foreground   #cde5ff
active_tab_background   #0b4a72
inactive_tab_foreground #c2c7cf
inactive_tab_background #181c20

color0  #101418
color8  #36393e
color1  #ffb4ab
color9  #ffb4ab
color2  #9acbfa
color10 #9acbfa
color3  #d2bfe7
color11 #d2bfe7
color4  #b9c8da
color12 #b9c8da
color5  #8c9198
color13 #8c9198
color6  #0b4a72
color14 #0b4a72
color7  #e0e2e8
color15 #c2c7cf
