background            #1b2122
foreground            #dee3e5
selection_foreground  #cee7ee
cursor                #84d2e6
url_color             #bec5eb
selection_background  #334a51
selection_foreground  #cee7ee
cursor_text_color     #003640

active_tab_foreground   #aaedff
active_tab_background   #004e5c
inactive_tab_foreground #bfc8cb
inactive_tab_background #171c1e

color0  #0f1416
color8  #343a3c
color1  #ffb4ab
color9  #ffb4ab
color2  #84d2e6
color10 #84d2e6
color3  #bec5eb
color11 #bec5eb
color4  #b2cbd2
color12 #b2cbd2
color5  #899295
color13 #899295
color6  #004e5c
color14 #004e5c
color7  #dee3e5
color15 #bfc8cb
