font_family Cascadia Mono
enable_audio_bell no
font_size 11.0
window_padding_width 15
cursor_trail 1

background_opacity 0.85
foreground #d4ddf9
background #1d1d2a
selection_foreground #1d1d2a
selection_background #f5ddd8

cursor #f5ddd8
cursor_text_color #1d1d2a

active_tab_foreground #1d1d2a
inactive_tab_background #1d1d2a
tab_bar_background #1d1d2a

color0 #414458
color8 #414458

color1 #f793af
color9 #f793af

color2  #a9e7a4
color10 #a9e7a4

color3  #fde6b5
color11 #fde6b5

color4  #8cb4fc
color12 #8cb4fc

color5  #f6c4e9
color13 #f6c4e9

color6  #97e6d9
color14 #97e6d9

color7  #cfd8f6
color15 #a3aaca
