$primary = {{colors.primary.default.rgb}}
$primaryContainer = {{colors.primary_container.default.rgb}}
$onPrimary = {{colors.on_primary.default.rgb}}
$onPrimaryContainer = {{colors.on_primary_container.default.rgb}}
$secondary = {{colors.secondary.default.rgb}}
$secondaryContainer = {{colors.secondary_container.default.rgb}}
$surface = {{colors.surface.default.rgb}}
$surfaceContainer = {{colors.surface_container.default.rgb}}
$surfaceContainerHigh = {{colors.surface_container_high.default.rgb}}
$surfaceVariant = {{colors.surface_variant.default.rgb}}
$onSurfaceVariant = {{colors.on_surface_variant.default.rgb}}
$text = {{colors.on_surface.default.rgb}}
$outline = {{colors.outline.default.rgb}}
$outlineVariant = {{colors.outline_variant.default.rgb}}
$error = {{colors.error.default.rgb}}
